"""礼之器游戏 · 10 个种子场景。

设计原则
- 当代真实生活情境，非古礼复刻
- 每场景 4 选项无单一标准答案，留反思空间
- 每选项有儒分(-3..+3) 和 情分(-3..+3) — 两者会冲突
- 每选项可解锁 1-2 句经典依据（解锁后进图鉴）
- 覆盖五类关系：daily(公共) / work(职场) / friend(朋友) / family(家庭) / school(校园)
"""
from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from .models import LiScenario


SCENARIOS = [
    # ── 公共空间 daily ─────────────────────────────────────────────
    {
        "title": "地铁让座",
        "category": "daily",
        "setting": "你在地铁上找了一个难得的座位。下一站，上来一位拄拐的老人，但你身旁还坐着一个看起来熬了几个通宵的程序员。你赶时间去面试。",
        "options": [
            {"key": "A", "text": "起身让给老人，自己站着继续看面经",
             "ru_delta": 2, "qing_delta": 2,
             "comment_ru": "直截的「敬」，符合「老吾老以及人之老」。",
             "comment_others": "老人感激；程序员若有所思。",
             "ref_ids": ["mengzi.lianghuiwang.1.7"]},
            {"key": "B", "text": "假装没看见，继续低头看手机",
             "ru_delta": -3, "qing_delta": -2,
             "comment_ru": "失「敬」，亦非「恕」。",
             "comment_others": "老人沉默接受；周围人侧目。",
             "ref_ids": ["lunyu.weizheng.2.7"]},
            {"key": "C", "text": "用胳膊轻轻碰碰程序员，示意他让",
             "ru_delta": -1, "qing_delta": -2,
             "comment_ru": "「不在其位，不谋其政」——越界要求他人尽你之礼。",
             "comment_others": "程序员尴尬抬头；老人不安。",
             "ref_ids": []},
            {"key": "D", "text": "自己起身让座，同时对程序员笑了笑：「我俩一起站？」",
             "ru_delta": 3, "qing_delta": 3,
             "comment_ru": "既尽己之礼，又顾及他人感受，近「忠恕」。",
             "comment_others": "老人感激；程序员被理解，主动也站起来。",
             "ref_ids": ["lunyu.liren.4.15", "lunyu.weilinggong.15.24"]},
        ],
        "related_concepts": ["jing", "shu", "ren"],
        "sort_order": 1,
    },

    # ── 职场 work ─────────────────────────────────────────────
    {
        "title": "聚餐听老板",
        "category": "work",
        "setting": "部门聚餐，老板兴致来了讲自己当年创业的故事，已经讲了 25 分钟。其他同事陆续低头吃菜。你正好坐在老板对面，他时不时看你。",
        "options": [
            {"key": "A", "text": "频频点头：「真的太有启发了！」「这就是格局！」",
             "ru_delta": -3, "qing_delta": 1,
             "comment_ru": "「巧言令色，鲜矣仁」。",
             "comment_others": "老板舒服；同桌侧目；你内心打折。",
             "ref_ids": ["lunyu.xueer.1.3"]},
            {"key": "B", "text": "认真听，偶尔点头，不发言",
             "ru_delta": 1, "qing_delta": 1,
             "comment_ru": "近「君子讷于言」。",
             "comment_others": "老板觉得你稳；同事觉得你正常。",
             "ref_ids": ["lunyu.liren.4.24"]},
            {"key": "C", "text": "找一个真实困惑的点向他请教",
             "ru_delta": 3, "qing_delta": 2,
             "comment_ru": "「敬而不谄」——以问代奉承，是高境界的礼。",
             "comment_others": "老板眼睛亮起来，话题进入实质。",
             "ref_ids": ["lunyu.shuer.7.21"]},
            {"key": "D", "text": "假装接电话出去 5 分钟",
             "ru_delta": -2, "qing_delta": -1,
             "comment_ru": "用诈术解决场合，「人而无信，不知其可」。",
             "comment_others": "老板回头注意到；同事羡慕但记心里。",
             "ref_ids": ["lunyu.weizheng.2.22"]},
        ],
        "related_concepts": ["jing", "xin", "junzi"],
        "sort_order": 2,
    },

    {
        "title": "同事邀功",
        "category": "work",
        "setting": "项目交付了。汇报会上，同事把你做的核心部分讲成了「我们一起搞的」，但用了 80% 的时间在讲他的部分。轮到你了。",
        "options": [
            {"key": "A", "text": "云淡风轻：「我没什么补充」",
             "ru_delta": 0, "qing_delta": 0,
             "comment_ru": "「君子讷于言」可以，但有时也是逃避自己的责任与表达。",
             "comment_others": "上级以为你真的没贡献；同事松一口气。",
             "ref_ids": ["lunyu.liren.4.24"]},
            {"key": "B", "text": "用事实补充：「这部分的实现细节是这样⋯」（不点名）",
             "ru_delta": 3, "qing_delta": 1,
             "comment_ru": "「君子喻于义」——用专业事实表达，不靠攻击。",
             "comment_others": "上级看到你的实力；同事尴尬但保面子。",
             "ref_ids": ["lunyu.liren.4.16"]},
            {"key": "C", "text": "当场指出：「这部分是我做的」",
             "ru_delta": 1, "qing_delta": -2,
             "comment_ru": "诚实，但失了「和而不同」的分寸。",
             "comment_others": "上级心里有数；同事对你怀恨。",
             "ref_ids": ["lunyu.zilu.13.23"]},
            {"key": "D", "text": "会后私下找同事「谈一谈」",
             "ru_delta": 2, "qing_delta": 1,
             "comment_ru": "「己所不欲，勿施于人」——给对方反思空间。",
             "comment_others": "同事可能承认；可能否认；但关系不破。",
             "ref_ids": ["lunyu.yanyuan.12.2"]},
        ],
        "related_concepts": ["yi", "he", "shu"],
        "sort_order": 3,
    },

    # ── 朋友 friend ─────────────────────────────────────────────
    {
        "title": "失恋朋友的质问",
        "category": "friend",
        "setting": "好友失恋后向你哭诉了一小时。她突然抬头问你：「你以前是不是就觉得他不靠谱？说真话。」",
        "options": [
            {"key": "A", "text": "「对，我早看他不行，渣男配不上你」",
             "ru_delta": -2, "qing_delta": 2,
             "comment_ru": "「巧言」之变体——短期讨好，不诚。",
             "comment_others": "她当下舒服，但日后会觉得朋友圈早知道而瞒她。",
             "ref_ids": ["lunyu.xueer.1.3"]},
            {"key": "B", "text": "「我了解不多，不好评价」",
             "ru_delta": 1, "qing_delta": -1,
             "comment_ru": "「知之为知之」，但失了仁。",
             "comment_others": "她觉得没被接住。",
             "ref_ids": ["lunyu.weizheng.2.17"]},
            {"key": "C", "text": "「你看到的他是真的他，我看到的也是」",
             "ru_delta": 2, "qing_delta": -1,
             "comment_ru": "诚，但不近人情。",
             "comment_others": "她沉默；可能日后想到这句话有触动。",
             "ref_ids": []},
            {"key": "D", "text": "「我先不评价他。你现在最难受的是哪一点？」",
             "ru_delta": 3, "qing_delta": 3,
             "comment_ru": "「恕」之极致：把焦点放回她身上。",
             "comment_others": "她真正被接住，哭出来；关系更近。",
             "ref_ids": ["lunyu.weilinggong.15.24", "lunyu.yanyuan.12.2"]},
        ],
        "related_concepts": ["shu", "ren", "xin"],
        "sort_order": 4,
    },

    {
        "title": "朋友炫富",
        "category": "friend",
        "setting": "三年没见的同学聚会，一开口就在讲他刚换的车、新买的房。其他人开始有点不自在。",
        "options": [
            {"key": "A", "text": "羡慕地配合：「真的好棒，你太厉害了」",
             "ru_delta": -1, "qing_delta": 1,
             "comment_ru": "「巧言令色」。",
             "comment_others": "他更兴奋；其他人更不自在。",
             "ref_ids": ["lunyu.xueer.1.3"]},
            {"key": "B", "text": "转移话题：「对了，你还玩篮球吗？」",
             "ru_delta": 2, "qing_delta": 2,
             "comment_ru": "「君子成人之美」——救他于失态。",
             "comment_others": "他下台阶；其他人感激。",
             "ref_ids": ["lunyu.yanyuan.12.16"]},
            {"key": "C", "text": "冷淡：「嗯」之后埋头吃菜",
             "ru_delta": -1, "qing_delta": -1,
             "comment_ru": "失了主动「成人之美」的机会。",
             "comment_others": "气氛更冷。",
             "ref_ids": []},
            {"key": "D", "text": "笑着调侃：「行了行了，你过的好不用每个细节说」",
             "ru_delta": 1, "qing_delta": 0,
             "comment_ru": "近「和而不同」，但口直有伤。",
             "comment_others": "他可能下意识收敛；可能不快。",
             "ref_ids": ["lunyu.zilu.13.23"]},
        ],
        "related_concepts": ["junzi", "he"],
        "sort_order": 5,
    },

    # ── 家庭 family ─────────────────────────────────────────────
    {
        "title": "父母的旧错",
        "category": "family",
        "setting": "你已经 30 岁，回家过年。妈妈又翻起小时候你考砸高考那件事，说「都怪你当年不听话」。其他亲戚都在听。",
        "options": [
            {"key": "A", "text": "「妈，这都过去 12 年了能不能不提了？」直接顶回去",
             "ru_delta": -2, "qing_delta": -2,
             "comment_ru": "失了「孝」。",
             "comment_others": "妈妈受伤，场面僵。",
             "ref_ids": ["lunyu.weizheng.2.7"]},
            {"key": "B", "text": "微笑听完，找机会转话题",
             "ru_delta": 2, "qing_delta": 1,
             "comment_ru": "近孝之「色难」——保持脸色。",
             "comment_others": "妈妈舒服一些；其他人体察出你的成长。",
             "ref_ids": ["lunyu.weizheng.2.8"]},
            {"key": "C", "text": "认真回应：「您当时挺不容易的，我现在懂」",
             "ru_delta": 3, "qing_delta": 3,
             "comment_ru": "孝的真义在「敬」与「理解」。",
             "comment_others": "妈妈眼眶红；亲戚动容。",
             "ref_ids": ["lunyu.weizheng.2.7", "lunyu.liren.4.17"]},
            {"key": "D", "text": "找借口去厨房帮忙离席",
             "ru_delta": 0, "qing_delta": -1,
             "comment_ru": "「事父母几谏」——回避不是答案。",
             "comment_others": "妈妈知道你在躲；亲戚以为你不孝。",
             "ref_ids": []},
        ],
        "related_concepts": ["xiao", "jing"],
        "sort_order": 6,
    },

    {
        "title": "父母过度操心",
        "category": "family",
        "setting": "你 25 岁，独立租房。妈妈每周打 3 次电话，每次反复叮嘱「记得吃药」「别熬夜」「找对象了没」。你这周特别忙。",
        "options": [
            {"key": "A", "text": "拒接，回短信「在开会」",
             "ru_delta": -2, "qing_delta": -2,
             "comment_ru": "失「色难」之礼。",
             "comment_others": "妈妈以为你嫌烦，越焦虑越打。",
             "ref_ids": ["lunyu.weizheng.2.8"]},
            {"key": "B", "text": "接起来速战速决：「好好好知道了」",
             "ru_delta": -1, "qing_delta": 0,
             "comment_ru": "形式上「养」了，但无「敬」。",
             "comment_others": "妈妈感觉敷衍。",
             "ref_ids": ["lunyu.weizheng.2.7"]},
            {"key": "C", "text": "主动每周日固定时间长电话，主动报告生活",
             "ru_delta": 3, "qing_delta": 3,
             "comment_ru": "「事父母几谏」的现代版——主动制度化的孝。",
             "comment_others": "妈妈安心；不再反复打。",
             "ref_ids": ["lunyu.xueer.1.6"]},
            {"key": "D", "text": "认真和妈妈讨论「你这么打我我有点累」",
             "ru_delta": 2, "qing_delta": 1,
             "comment_ru": "「几谏」——温和地说。诚但需技巧。",
             "comment_others": "妈妈可能委屈，可能反思。",
             "ref_ids": []},
        ],
        "related_concepts": ["xiao", "jing"],
        "sort_order": 7,
    },

    # ── 校园 / 学习 school ─────────────────────────────────────────────
    {
        "title": "同学考试求看",
        "category": "school",
        "setting": "期末考试，监考是个新老师明显不严。前排同学转过头悄悄示意「给看一眼」。这是你的好朋友。",
        "options": [
            {"key": "A", "text": "假装没看见，正常答题",
             "ru_delta": 2, "qing_delta": -1,
             "comment_ru": "守「信」。",
             "comment_others": "朋友失望；可能埋怨。",
             "ref_ids": ["lunyu.weizheng.2.22"]},
            {"key": "B", "text": "歪过试卷给他看",
             "ru_delta": -3, "qing_delta": 2,
             "comment_ru": "「失信」——一时义气是「小人喻于利」。",
             "comment_others": "他短期感激，长期看你「这朋友靠不住」。",
             "ref_ids": ["lunyu.liren.4.16"]},
            {"key": "C", "text": "考完后主动找他补讲",
             "ru_delta": 3, "qing_delta": 2,
             "comment_ru": "「君子成人之美，不成人之恶」。",
             "comment_others": "他反而尊重你；学到东西。",
             "ref_ids": ["lunyu.yanyuan.12.16"]},
            {"key": "D", "text": "举手叫老师过来",
             "ru_delta": 0, "qing_delta": -3,
             "comment_ru": "「君子不党」可贵，但此举伤朋友为「不仁」。",
             "comment_others": "他被处分；友情破裂；其他人觉得你冷漠。",
             "ref_ids": ["lunyu.weilinggong.15.24"]},
        ],
        "related_concepts": ["xin", "yi", "junzi"],
        "sort_order": 8,
    },

    # ── 公共讨论 public ─────────────────────────────────────────────
    {
        "title": "群里被攻击",
        "category": "public",
        "setting": "你在一个 200 人的工作群里分享了一篇文章。一个不熟的人立刻在群里说「这种东西也信？太肤浅了」，并 @ 了你。",
        "options": [
            {"key": "A", "text": "立刻反击：「你才肤浅」",
             "ru_delta": -3, "qing_delta": -2,
             "comment_ru": "「以怒报怨」违「克己」。",
             "comment_others": "群里围观尴尬；你显得情绪化。",
             "ref_ids": ["lunyu.yanyuan.12.1"]},
            {"key": "B", "text": "私聊问他：「你具体觉得哪里有问题？想多请教」",
             "ru_delta": 3, "qing_delta": 1,
             "comment_ru": "「敬」与「学」并用；不在公开场合伤他面子。",
             "comment_others": "他可能解释，可能尴尬；其他人不知道，避免群体围观。",
             "ref_ids": ["lunyu.gongyechang.5.10", "lunyu.yanyuan.12.1"]},
            {"key": "C", "text": "在群里回：「您愿意展开说说不同意见吗？」",
             "ru_delta": 2, "qing_delta": 0,
             "comment_ru": "「和而不同」的展示，但公开提问对他是压力。",
             "comment_others": "群里其他人欣赏；他可能下不来台。",
             "ref_ids": ["lunyu.zilu.13.23"]},
            {"key": "D", "text": "不回应，默默退群",
             "ru_delta": -1, "qing_delta": -1,
             "comment_ru": "回避是另一种失礼。",
             "comment_others": "群里议论；你显得脆弱。",
             "ref_ids": []},
        ],
        "related_concepts": ["keji", "he", "jing"],
        "sort_order": 9,
    },

    {
        "title": "网约车的等待",
        "category": "daily",
        "setting": "你叫的网约车 20 分钟才到。司机一上来就抱怨「路太堵了，今天太不顺了」。你赶着开会。",
        "options": [
            {"key": "A", "text": "冷淡：「赶时间，麻烦开快点」",
             "ru_delta": -1, "qing_delta": -2,
             "comment_ru": "失了「敬」，且违「不在其位」——他不能控制堵车。",
             "comment_others": "司机情绪更差，开车更糟。",
             "ref_ids": []},
            {"key": "B", "text": "敷衍一句：「嗯嗯」之后看手机",
             "ru_delta": 0, "qing_delta": 0,
             "comment_ru": "未失，亦未尽。",
             "comment_others": "司机自顾自抱怨。",
             "ref_ids": []},
            {"key": "C", "text": "认真回应：「确实，今天可能是节前一天」",
             "ru_delta": 2, "qing_delta": 3,
             "comment_ru": "「四海之内皆兄弟」——对陌生人的小礼亦是仁。",
             "comment_others": "司机情绪平复；开车更稳；可能愿意走小路省时间。",
             "ref_ids": ["lunyu.yanyuan.12.5"]},
            {"key": "D", "text": "建议他：「你应该提前规划路线」",
             "ru_delta": -2, "qing_delta": -2,
             "comment_ru": "「不在其位，不谋其政」之失；以教训代理解。",
             "comment_others": "司机不悦；气氛尴尬。",
             "ref_ids": []},
        ],
        "related_concepts": ["jing", "ren"],
        "sort_order": 10,
    },
]


def seed_li_scenarios_if_empty(db: Session) -> int:
    if db.execute(select(LiScenario).limit(1)).first():
        return 0
    for s in SCENARIOS:
        db.add(LiScenario(**s))
    db.commit()
    return len(SCENARIOS)
